pipeline {
    agent any

    }

    stages {

      stage('run ansible playbook') {
          steps {
             {
                sh """
                Python-DevOps/Python
                ansible-playbook playbook.yml
                """
              }
          }
      }

      
}