pipeline {
    agent any

    stages {
        stage('Run Ansible Playbook') {
            steps {
                bat """
                cd Python-DevOps\\Python
                ansible-playbook playbook.yml
                """
            }
        }
    }
}
