pipeline {
    agent any

    }

    stages {

      stage('run ansible playbook') {
          steps {
                sh """
                cd Python-DevOps/Python
                ansible-playbook playbook.yml
                """
              
          }
      }

      
}