apiVersion: v1
kind: Service
metadata:
  name: survey-app
  labels:
    app: python-code
spec:
  selector:
    app: python-code
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - port: 8000 
    targetPort: 8000
    nodePort: 30000