pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
                // Add --password-stdin to run docker login command non-interactively
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd ..
                cd ..
                cd Python
                ansible-playbook ansible-playbook.yml
                """
            }
        }
        stage('Create a Cluster') {
            steps {
                script{
                    build job: 'Create_Cluster',
                    parameters: [
                    [ $class: 'StringParameterValue', name: 'Cluster']    
                    ]
                    
                } 
            } 
        }
    } 
}