---
- name: "Automate Docker Build using Ansible"
  hosts: localhost
  tasks:
  - name: stop running container 
    command: docker stop django-container 
    ignore_errors: true

  - name: remove stopped container 
    command: docker rm django-container
    ignore_errors: true

### Make sure to change the image name in the next tasks with your dockerhub username and repository name

  - name: remove used image 
    command: docker rmi python-code
    ignore_errors: true

  - name: build new image 
    command: docker build -t python-code .

  - name: tag the docker image  
    command: docker tag python-code brcee/python-code:latest
  
  - name: push docker image  
    command: docker push brcee/python-code

  - name: run new container
    command: docker run -d --name django-container -p 4000:8000 brcee/python-code

  - name: create a deployment in kubernetes
    shell: cd Python-DevOps/k8s; kubectl apply -f deployment.yaml

  - name: create a service in kubernetes
    command: kubectl apply -f services.yaml


